application:
  name: "Interview HQ"
  code: interview_hq

banner:
  location: app/banner.txt

spring:
  main:
    show-banner: true

  thymeleaf:
    check-template-location: true
    enabled: true
    cache: false

  jpa:
    database: mysql
    show-sql: false
    hibernate.ddl-auto: create-drop

  datasource:
    name: interview_hq
    database: mysql
    url: jdbc:mysql://localhost/interview_hq
    username: boot_u
    password: b00t!ful

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

  data:
    rest:
      base-uri: /data/rest/v1/

logging:
  file: ${application.code}.log

  level:
    org.springframework.web: WARN
    org.springframework.data: WARN
    org.springframework.boot: WARN
    org.hibernate: ERROR

server:
  port: 8089

flyway:
  enabled: true
  check-location: true
  locations:
    - classpath:db/migration
  baseline-on-migrate: true
